BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Grades" (
	"Id"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	"Nom"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Specialisations" (
	"Id"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	"Nom"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Unites" (
	"Id"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	"Nom"	TEXT NOT NULL,
	"UnitSpe"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Infractions" (
	"Id"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	"Nom"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Vehicules" (
	"Id"	INTEGER NOT NULL,
	"VehSpe"	TEXT NOT NULL,
	"Nom"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Actions" (
	"Id"	INTEGER NOT NULL,
	"Nom"	TEXT NOT NULL,
	"ActInfraction"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Effectifs" (
	"Id"	INTEGER NOT NULL,
	"IdDiscord"	TEXT NOT NULL,
	"Nom"	TEXT NOT NULL,
	"Prenom"	TEXT NOT NULL,
	"EffGrade"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
